# Generated by Django 5.2.5 on 2025-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=15)),
                ('series', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('country_code', 'series', 'year')},
            },
        ),
    ]
